export const programmingLanguages = [
  "bash",
  "c",
  "cpp",
  "css",
  "dart",
  "django",
  "dockerfile",
  "dos",
  "dsconfig",
  "excel",
  "fortran",
  "go",
  "java",
  "javascript",
  "json",
  // "juliaRepl (julia-repl)",
  // "julia",
  "kotlin",
  // "lasso",
  "latex",
  // "ldif",
  // "leaf",
  "less",
  // "lisp",
  // "livecodeserver",
  // "livescript",
  // "llvm",
  // "lsl",
  // "lua",
  // "makefile",
  "markdown",
  // "mathematica",
  // "matlab",
  // "maxima",
  // "mel",
  // "mercury",
  // "mipsasm",
  // "mizar",
  // "mojolicious",
  // "monkey",
  // "moonscript",
  // "n1ql",
  // "nginx",
  // "nim",
  // "nix",
  // "nodeRepl (node-repl)",
  // "nsis",
  // "objectivec",
  // "ocaml",
  // "openscad",
  // "oxygene",
  // "parser3",
  // "perl",
  // "pf",
  // "pgsql",
  // "phpTemplate (php-template)",
  "php",
  "plaintext",
  // "pony",
  "powershell",
  // "processing",
  // "profile",
  "prolog",
  // "properties",
  // "protobuf",
  // "puppet",
  // "purebasic",
  // "pythonRepl (python-repl)",
  "python",
  // "q",
  // "qml",
  // "r",
  // "reasonml",
  // "rib",
  // "roboconf",
  // "routeros",
  // "rsl",
  "ruby",
  // "ruleslanguage",
  // "rust",
  "sas",
  // "scala",
  // "scheme",
  // "scilab",
  "scss",
  "shell",
  // "smali",
  // "smalltalk",
  // "sml",
  // "sqf",
  "sql",
  // "stan",
  // "stata",
  // "step21",
  // "stylus",
  // "subunit",
  // "swift",
  // "taggerscript",
  // "tap",
  // "tcl",
  // "thrift",
  // "tp",
  // "twig",
  "typescript",
  // "vala",
  // "vbnet",
  // "vbscriptHtml (vbscript-html)",
  // "vbscript",
  // "verilog",
  // "vhdl",
  // "vim",
  // "x86asm",
  // "xl",
  "xml",
  "xquery",
  "yaml",
  // "zephir",
];
